import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/sosmed";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { poppins, seriftext, editorialItalic, editorialRegular, ivyPrestoLight, jakarta, inter, manrope } from "@/components/font/fonts";
import Header from '@/components/header';
import PageTransition from "@/components/pagetransition/PageTransition";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`hide-scrollbar ${poppins.variable} ${seriftext.variable} ${editorialItalic.variable} ${editorialRegular.variable} ${ivyPrestoLight.variable} ${jakarta.variable} ${inter.variable} ${manrope.variable} antialiased`}>
        <PageTransition>
          <ThemeProvider attribute="class" defaultTheme="light">
            <TooltipProvider delayDuration={0}>
              <Header />
              {children}
              <Navbar />
            </TooltipProvider>
          </ThemeProvider>
        </PageTransition>
      </body>
    </html>
  );
}
